server:
  port: 8001
#  address: 10.203.204.120
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # todo: 后序改成自己的数据库 - 账户 - 密码
    url: jdbc:mysql://43.143.138.8:3306/contest?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 262585mysql
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)